sonar.projectKey=lcn-frontend
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, build/**, .svelte-kit/**, public/**, **/*.test.*, **/*.spec.*
sonar.coverage.exclusions=src/main.tsx, src/App.tsx, src/vite-env.d.ts, **/*.d.ts, **/*.css, src/assets/**, src/types/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
