CREATE USER lcn_user IDENTIFIED BY lcn_pass_2026 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO lcn_user;
GRANT CONNECT, RESOURCE TO lcn_user;

COMMIT;