services:

  oracle-xe:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle_lcn_db
    ports:
      - "${ORACLE_PORT}:1521"
      - "5501:5500"
    environment:
      - ORACLE_PASSWORD=${ORACLE_ADMIN_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes:
  oracle_data: