services:

  oracle-xe:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle_lcn_db
    ports:
      - "${ORACLE_PORT}:1521"
      - "5501:5500"
    environment:
      - ORACLE_PASSWORD=${ORACLE_ADMIN_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  backend:
    build:
      context: ./backend-lcn-api/lcn-api
    container_name: lcn_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-xe:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=lcn_user
      - SPRING_DATASOURCE_PASSWORD=lcn_pass_2026
    depends_on:
      oracle-xe:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: lcn_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  oracle_data: